services:
  db:
    image: mysql/mysql-server:8.0
    container_name: mysql-bank-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_USER: bank_user
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_DATABASE: banking_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: maven:3.9.5-eclipse-temurin-17
    container_name: java-bank-dev-app
    depends_on:
      - db
    working_dir: /app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/banking_db
      SPRING_DATASOURCE_USERNAME: bank_user
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      MAVEN_OPTS: "-XX:MaxRAMPercentage=75.0"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: mvn compile spring-boot:run

volumes:
  mysql_data: